### ISSUE TITLE
Consider reverting emoji addition

### ISSUE THREAD

**Issue by acorncom** [skaterdav85/ember-cli-doorkeeper#5]
I'm a big fan of Unicode in CI (and the resulting emoji we get to use). That said, not all infrastructure supports it well yet. The hamster emoji was recently removed from Ember-CLI here (https://github.com/ember-cli/ember-cli/issues/7426) due to some issues surrounding it. Should we follow suit here?

**Comment by iamdtang** [comment]
Good point! I'll remove them and make those messages configurable so for those who want it can have it 🙂

**Comment by iamdtang** [comment]
Released in 0.1.5. Thanks for the suggestion!
